name: Pytest

defaults:
  run:
    # To load bashrc
    shell: bash -ieo pipefail {0}

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [main, dev]
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

        # Used by ci_test.sh
    - name: Install dependencies
      run: |
        python setup.py install
        pip install pytest
        pip install pytest-cov
    - name: Run value set analysis tests
      run: |
        pytest python_tests/value_set_analysis.py